In [129]:
import pathlib
import shutil
from math import ceil, sqrt
from pathlib import Path
from typing import Callable, List, Optional, Tuple, Any, Sequence

import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import PIL
import pyrootutils
import torch
import torchvision.transforms as T
import torchvision.transforms.functional as F
from skimage.metrics import structural_similarity
from sklearn.model_selection import GroupShuffleSplit
from torch.utils.data import ConcatDataset, Dataset
from torchvision.io import read_image
from tqdm import tqdm
from torchmetrics import Metric

root = pyrootutils.setup_root(search_from=".", indicator=".project-root", pythonpath=True)

from src.data.components.dataset import FetalPlanesDataset, USVideosDataset
from src.data.utils.utils import show_numpy_images, show_pytorch_images
from src.models.fetal_module import FetalLitModule

root

PosixPath('/home/zamojskia/ultrasound_fetal_images')

In [97]:
torch.randint(0, 3, [])

tensor(2)

In [118]:
torch.randint(0, 3, (1,))

tensor([2])

In [46]:
a = [1, 2, 3]
i = torch.randint(0, 3, (1,))

a[i]

3

In [55]:
x = torch.tensor([1], dtype=torch.float32)
print(x)
print(torch.mean(torch.cat([x])))
print(torch.mean(torch.cat([x,x,x])))

tensor([1.])
tensor(1.)
tensor(1.)


In [57]:
x = torch.tensor([[1,2,3]], dtype=torch.float32)
print(x)
print(torch.mean(torch.cat([x]), dim=0))
print(torch.mean(torch.cat([x,x,x]), dim=0))

tensor([[1., 2., 3.]])
tensor([1., 2., 3.])
tensor([1., 2., 3.])


In [200]:
torch.exp(torch.tensor(float('-inf')))

tensor(0.)

In [202]:
loss = torch.nn.CrossEntropyLoss()

x = torch.tensor([[0., 0., 0.]])
y = torch.tensor([1])
loss(x, y)

tensor(1.0986)

In [203]:
loss = torch.nn.CrossEntropyLoss()

x = torch.tensor([[float('-inf'), float('-inf'), 0., 0., 0.]])
y = torch.tensor([3])
loss(x, y)

tensor(1.0986)

In [213]:
softmax = torch.nn.Softmax(dim=1)

x = torch.tensor([[0., 0., 0.]])
softmax(x)

tensor([[0.3333, 0.3333, 0.3333]])

In [214]:
softmax = torch.nn.Softmax(dim=1)

x = torch.tensor([[float('-inf'), float('-inf'), 0., 0., 0.]])
softmax(x)

tensor([[0.0000, 0.0000, 0.3333, 0.3333, 0.3333]])

In [225]:
x = torch.tensor([[0., 0., 0., 0., 0.]])
mask = torch.tensor([1, 1, 0, 0, 0])
torch.masked_fill(x, mask, value=float('-inf'))

tensor([[-inf, -inf, 0., 0., 0.]])

In [234]:
masks = torch.nn.functional.one_hot(torch.arange(0, 3), num_classes=5)
print(len(masks))
masks

3


tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0]])

In [229]:
x = torch.tensor([[0., 0., 0., 0., 0.]])
mask = torch.tensor([1, 1, 0, 0, 0], dtype=torch.bool)
x.masked_fill(mask, value=float('-inf'))

tensor([[-inf, -inf, 0., 0., 0.]])

In [236]:
for i, c in enumerate(torch.tensor([1, 1, 0, 0, 0], dtype=torch.bool)):
    if c:
        print(i)

0
1
